apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secrets
  namespace: task-manager
type: Opaque
stringData:
  DATABASE_URL: "postgres://taskmanager:CHANGE_ME@postgres-service:5432/taskmanager_db"
  JWT_PRIVATE_KEY: "PASTE_YOUR_PRIVATE_KEY_HERE"
  JWT_PUBLIC_KEY: "PASTE_YOUR_PUBLIC_KEY_HERE"
  SENTRY_DSN: ""
